'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { SectionWrapper } from '@/components/shared/PageHeader';
import { cn } from '@/lib/utils';

const faqs = [
  {
    q: 'How does the AI generation queue work?',
    a: 'When you submit a generation request, it\'s added to a BullMQ Redis queue. The priority is determined by your role — ADMIN gets priority 1, MANAGER gets priority 2, and USER gets priority 3. You can poll the job status using the returned jobId, and the frontend automatically tracks completion.',
  },
  {
    q: 'Which AI models are supported?',
    a: 'We support GPT-4o, GPT-4o Mini (OpenAI) and Gemini 1.5 Flash, Gemini 1.5 Pro (Google). You can select the model per generation request. The default is GPT-4o Mini for cost efficiency.',
  },
  {
    q: 'What is the team management feature?',
    a: 'MANAGER role users can view all content generated by their assigned team members, see team usage analytics, and track token consumption across the team. ADMIN users have full system-wide visibility.',
  },
  {
    q: 'How does credit usage work?',
    a: 'Each AI generation consumes credits from your balance. Credits are also tracked via token usage per request in the ApiUsage table. You can monitor remaining credits on your dashboard or via the /api/v1/stats/usage endpoint.',
  },
  {
    q: 'Is the generated content SEO-optimized?',
    a: 'Yes. Every generation includes structured metadata: an SEO score (0–100), keyword suggestions, reading time estimate, and word count. These are stored in the Content.metadata JSON field and displayed on the content detail view.',
  },
  {
    q: 'Can I regenerate content?',
    a: 'Yes. From the History page, you can open any content item and trigger a regeneration with the same prompt and settings. This creates a new generation job and preserves the original.',
  },
  {
    q: 'What happens if a generation fails?',
    a: 'BullMQ tracks failed jobs and exposes the failure reason via the /api/v1/ai/job-status/:id endpoint. The frontend polls this and surfaces the error message so you can retry or adjust your prompt.',
  },
  {
    q: 'Is there a rate limit?',
    a: 'Yes — USER role: 15 requests/hour, 80/day. MANAGER role: 40/hour, 200/day. ADMIN has no rate limit. These are enforced server-side with express-rate-limit.',
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="border-b border-border last:border-0"
    >
      <button
        className="flex w-full items-center justify-between gap-4 py-5 text-left text-sm font-semibold hover:text-primary transition-colors"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
      >
        {q}
        <ChevronDown
          className={cn('h-4 w-4 shrink-0 text-muted-foreground transition-transform duration-200', open && 'rotate-180')}
        />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-sm text-muted-foreground leading-relaxed">{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export function FAQSection() {
  return (
    <SectionWrapper>
      <div className="text-center mb-12">
        <p className="text-sm font-semibold uppercase tracking-widest text-primary">FAQ</p>
        <h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">
          Frequently asked questions
        </h2>
      </div>

      <div className="mx-auto max-w-3xl rounded-2xl border border-border bg-card px-6">
        {faqs.map((item) => (
          <FAQItem key={item.q} q={item.q} a={item.a} />
        ))}
      </div>
    </SectionWrapper>
  );
}
